import { Team } from './Team';
import { Player } from './Player';

export const EVENTS_IDS = {
  START_MATCH_EVENT_ID: 122,
  START_PERIOD_EVENT_ID: 121,
  WON_JUMP_EVENT_ID: 178,
  LOST_JUMP_EVENT_ID: 179,
  TURNOVER_EVENT_ID: 106,
  STEAL_EVENT_ID: 103,
  THREE_POINTS_SHOT_MISSED_EVENT_ID: 98,
  DEFENSIVE_REBOUND_EVENT_ID: 104,
  TWO_POINTS_SHOT_MADE_EVENT_ID: 93,
  THREE_POINTS_SHOT_MADE_EVENT_ID: 94,
  TWO_POINTS_SHOT_MISSED_EVENT_ID: 97,
  FOUL_NO_FT_EVENT_ID: 159,
  FOUL_RECEIVED_EVENT_ID: 110,
  ASSIST_THREE_POINTS_SHOT_EVENT_ID: 108,
  OFFENSIVE_REBOUND_EVENT_ID: 101,
  ASSIST_TWO_POINTS_SHOT_EVENT_ID: 107,
  FAST_BREAK_TWO_POINTS_EVENT_ID: 130,
  OFFENSIVE_FOUL_EVENT_ID: 109,
  SUBSTITUTION_OUT_EVENT_ID: 115,
  SUBSTITUTION_IN_EVENT_ID: 112,
  BLOCK_RECEIVED_EVENT_ID: 105,
  BLOCK_EVENT_ID: 102,
  FOUL_TWO_FT_EVENT_ID: 161,
  FREE_THROW_MADE_EVENT_ID: 92,
  END_OF_THE_QUARTER_EVENT_ID: 116,
  FREE_THROW_MISSED_EVENT_ID: 96,
  TIMEOUT_EVENT_ID: 113,
  FOUL_ONE_FT_EVENT_ID: 160,
  DUNK_EVENT_ID: 100,
  ASSIST_FOUL_RECEIVED_EVENT_ID: 119,
  FAST_BREAK_THREE_POINTS_EVENT_ID: 131,
  END_MATCH_EVENT_ID: 123,
}

export interface MatchEvent {
  eventType: number,
  team: Team,
  player: Player | null,
  periodId: number,
  crono: string,
  minute: number,
  second: number,
  localScore: number,
  visitorScore: number,
  description: string,
  localEvent: boolean
}

export function isMatchEventPlayByPlayValid(matchEvent: MatchEvent): boolean {
  switch (matchEvent.eventType) {
    case EVENTS_IDS.START_PERIOD_EVENT_ID:
    case EVENTS_IDS.WON_JUMP_EVENT_ID:
    case EVENTS_IDS.LOST_JUMP_EVENT_ID:
    case EVENTS_IDS.TURNOVER_EVENT_ID:
    case EVENTS_IDS.STEAL_EVENT_ID:
    case EVENTS_IDS.THREE_POINTS_SHOT_MISSED_EVENT_ID:
    case EVENTS_IDS.DEFENSIVE_REBOUND_EVENT_ID:
    case EVENTS_IDS.TWO_POINTS_SHOT_MADE_EVENT_ID:
    case EVENTS_IDS.THREE_POINTS_SHOT_MADE_EVENT_ID:
    case EVENTS_IDS.TWO_POINTS_SHOT_MISSED_EVENT_ID:
    case EVENTS_IDS.FOUL_NO_FT_EVENT_ID:
    case EVENTS_IDS.FOUL_RECEIVED_EVENT_ID:
    case EVENTS_IDS.ASSIST_THREE_POINTS_SHOT_EVENT_ID:
    case EVENTS_IDS.OFFENSIVE_REBOUND_EVENT_ID:
    case EVENTS_IDS.ASSIST_TWO_POINTS_SHOT_EVENT_ID:
    case EVENTS_IDS.FAST_BREAK_TWO_POINTS_EVENT_ID:
    case EVENTS_IDS.OFFENSIVE_FOUL_EVENT_ID:
    case EVENTS_IDS.SUBSTITUTION_OUT_EVENT_ID:
    case EVENTS_IDS.SUBSTITUTION_IN_EVENT_ID:
    case EVENTS_IDS.BLOCK_RECEIVED_EVENT_ID:
    case EVENTS_IDS.BLOCK_EVENT_ID:
    case EVENTS_IDS.FOUL_TWO_FT_EVENT_ID:
    case EVENTS_IDS.FREE_THROW_MADE_EVENT_ID:
    case EVENTS_IDS.END_OF_THE_QUARTER_EVENT_ID:
    case EVENTS_IDS.FREE_THROW_MISSED_EVENT_ID:
    case EVENTS_IDS.TIMEOUT_EVENT_ID:
    case EVENTS_IDS.FOUL_ONE_FT_EVENT_ID:
    case EVENTS_IDS.DUNK_EVENT_ID:
    case EVENTS_IDS.ASSIST_FOUL_RECEIVED_EVENT_ID:
    case EVENTS_IDS.FAST_BREAK_THREE_POINTS_EVENT_ID:
      return true;
    default:
      return false;
  }
}

export function isMatchEventScored(matchEvent: MatchEvent): boolean {
  switch (matchEvent.eventType) {
    case EVENTS_IDS.TWO_POINTS_SHOT_MADE_EVENT_ID:
    case EVENTS_IDS.THREE_POINTS_SHOT_MADE_EVENT_ID:
    case EVENTS_IDS.FREE_THROW_MADE_EVENT_ID:
      return true;
    default:
      return false;
  }
}